### ISSUE TITLE
Read Version from Configuration File

### ISSUE THREAD

**Issue by bvfnbk** [bvfnbk/planning-poker#20]
Define a manifest defining all required versions, e.g.

```yaml
---
planning-poker:
  application: 1.2.3
  modules:
    frontend: 2.3.4
    gateway: 1.0.0
    signaling: 3.4.5
```

These versions are _automatically_ used in

- `composition.yaml`
- `build.sh` script (making the version argument optional)
- Badges in the read-me files.
- etc.
